### ISSUE TITLE
How to change selected date background color and Stop dismissing view on click of dates

### ISSUE THREAD

**Issue by CearsKhush** [DevYeom/YYCalendar#17]
Hey @DevYeom, Thank you for this amazing library but I am facing some issues I want to change background color of selected date with Circle I had tried to change using following code but I won't be able to change it and I had comment every dismiss view method but then also view is getting dismissed I want to dismiss the view on specific button not on selected date. Please help!

![Screenshot 2019-08-02 at 3 58 14 PM](https://user-images.githubusercontent.com/49678377/62364144-6c3c4600-b53e-11e9-8cce-b6975d05d26c.png)

**Comment by DevYeom** [comment]
Thanks for this issue 😃
I got you. So I will add some public properties to set background color of selected date and a dismissing option.

p.s. Please click a star for me and come again soon😎

**Comment by CearsKhush** [comment]
Thanks for instant reply, I will Appreciate you work and please ping me once you made changes.

**Comment by DevYeom** [comment]
@CearsKhush 
Hello!! Sorry for late!
I updated 1.2.1 to customize dayButtonStyle, selectedDayColor for you.
you just code as below.

```swift
calendar.dayButtonStyle = .circle
calendar.selectedDayColor = UIColor
```

But I didn't add the way you said the calendar disappeared. Because I have a plan to add a new calendar component in the next version, as you said.

**Comment by CearsKhush** [comment]
@DevYeom Thank you soo Much :)
