### ISSUE TITLE
Wrong CHN LangType

### ISSUE THREAD

**Issue by smartyu** [DevYeom/YYCalendar#23]
Thank you for your YYCalendar，but you make wrong with langType.

["日", "月", "火", "水", "木", "金", "土"]
This is Japanese  week.

Chinese week is as following. 
["日", "一", "二", "三", "四", "五", "六"]

please update your code, thank you so much!

**Comment by DevYeom** [comment]
Oh.. i'm so sorry.
I will update quickly.
Thank you very much :)
