### ISSUE TITLE
[Question] keyWindow Deprecated?

### ISSUE THREAD

**Issue by dp221125** [DevYeom/YYCalendar#28]
keyWinodw is deprecated. May I continue using it?

https://developer.apple.com/documentation/uikit/uiapplication/1622924-keywindow

**Comment by DevYeom** [comment]
Sorry, I'm so late to see your issue.
Thank you for this window issue. 👍 
Please check [1.3.2](https://github.com/DevYeom/YYCalendar/releases/tag/1.3.2)
