### ISSUE TITLE
Landscape mode bad view

### ISSUE THREAD

**Issue by aksenkin** [DevYeom/YYCalendar#29]
In landscape mode (iPhone, iOS 13) the calendar cannot be resized to take proportional place.

**Comment by DevYeom** [comment]
Thank you for landscape issue. 😀
Please check [1.3.2](https://github.com/DevYeom/YYCalendar/releases/tag/1.3.2)

**Comment by aksenkin** [comment]
Thank you for your calendar and efforts. In case you will add the Russian version of the calendar somewhen, it would be great.

**Comment by DevYeom** [comment]
@aksenkin 
You have given me a good inspiration.
I updated customizable langType.
Please check [1.3.3](https://github.com/DevYeom/YYCalendar/releases/tag/1.3.3)

p.s. If you give me a star, i really appreciate. 🤩
